### PR TITLE
Wrath Compatibility Updates

### PR DESCRIPTION
**Pull request by glajchs**
Though functional for creating class templates as well as applying them, the code is NOT cleaned up and fully tested yet.  We will want to squash merge this to get some of the in between/investigatory changes done on the branch when it's finally brought back.

Spell descriptions need fixing for all classes that aren't druid (druid is done).

### CODE REVIEW

**Comment by knasen88** [comment]
could this perhaps get merged into a wrath branch so we can dl it?

**Comment by Lethay** [comment]
> could this perhaps get merged into a wrath branch so we can dl it?

Without the Beta, I cannot test it and I'm not comfortable merging a pull request that I cannot verify. You are of course welcome to manually download it!

**Comment by glajchs** [comment]
**Help Required**

As the writer of the work in progress changes, I have to agree that they aren't ready.  I simply haven't found the time to come back to this.  A busy schedule (plus being addicted to wow) just didn't make it happen.  And I'm going on vacation today until the week after pre-patch, and this needs to be finished before then.
More information can be found in the original github issue as well, but here's my state of where it's at.

I've gotten the addon to where it can successfully use and apply talent trees.
All that remains is that the trees themselves need to be filled out.

Only the druid tree is completely done (this was my test case).

I was mid-way through trying to make the talent exporter Better™, and I was unable to finish it.  Basically wow has changed how the talents are sorted and it's a pain in the neck.  But the exporter (as documented on the site) DOES work, it'll just not have the proper set of tooltips for each talent.

_Most_ talents will automatically have their tooltips sorted and working, but underneath the covers, sometimes it grabs too many (or prunes out too many) tooltips, or they are out of order.  I also haven't fixed a bug where it's misordering tooltips with floating points in them (0.5 rage, 1 rage, 1.5 rage, etc something like that).
What you have to do for each class is:
1. Run the exporter and paste in the talents as required.
2. Load up the UI and mouse over each one to see if a specific talent's tooltip is "bad" in some way.
3. Run some combination of `/script Talented.GetSpellsMatching("TALENT_NAME")` in the chat, or `/script Talented.ParseTalent("TALENT_NAME")`, and figure out which spellids are the correct tooltip spellids.  If you get stuck, wrath's wowhead has the actual spellids for the tooltips.  Just search the talent name and find the ones labeled "talent".
4. Go back into the source for each class's file and input the updated tooltip ids

One final tweak I'd like to see someone make is ensuring that the tooltips all get looked up before you mouse over them in the UI, which will prevent you needing to mouse over several times.  Someone put a code snippet in the issue here, but I haven't been able to try it out yet.
https://github.com/Lethay/TalentedClassic/issues/62

Finally, the code is a bit messy.  I tried out some very crazy logic to try and auto generate the tooltip ordering, and it's not 100% yet.  There's lots of print statements that should be cleaned up, and I've imported the DevTools_Dump utility in whole in the addon, and once it's working we should remove that most likely.

I am however hopeful that someone can grab the time to get the list of proper tooltip Ids imported alongside the rest of the generated talents.  With that change + the tooltip rendering fix, it should be good enough for people to use in pre-patch.

Again, only the druid tree is 100% done.

So sorry to leave it like this!  I really wanted to make this great, but only had time to get it 80% there.

Feel free to steal from or fork my git repo.  I don't care about any licensing/attribution stuff, whatever, just get this working and in the hands of fellow players! :heart:

**Comment by TimothyLuke** [comment]
Is there an update on this now that PTR has been updated to Wrath?

**Comment by glajchs** [comment]
I'm back from vacation (though for family reason I won't be around many nights this week).
Regardless I got all of the class data imported so you should be able to make talent trees for, and apply them to, all the classes in wrath!

Now we just need to add (re-enable) dual spec and glyph support, and clean stuff up and such.

Give it a try, you should be able to use it on the beta (and maybe PTR).

**Comment by Lethay** [comment]
Thanks a lot. I only just got a chance to do stuff myself - you beat me by a day! I checked it, it works for me. I added dual-spec and glyph support. We still need to clean up, because Talented_Data is no longer needed, but I'll get to it in time.

**Comment by glajchs** [comment]
> Thanks a lot. I only just got a chance to do stuff myself - you beat me by a day! I checked it, it works for me. I added dual-spec and glyph support. We still need to clean up, because Talented_Data is no longer needed, but I'll get to it in time.

Awesome, thanks Lethay!

Let me know if you want me to clean up any of the stuff I wrote, it was a rush job.
If not I'm happy to go back to Talented enthusiast/wow addict :-)

**Pull request merged**
