### PR TITLE
fixes for sod p4 launch

### LINKED ISSUE #133: Broken w/ SOD P4
image

image

Talented window just won't come up with today's updates.

### PR DESCRIPTION
**Pull request by mrchops1024**
- Update .toc 
- Update return values for `GetTalentTabInfo()`

Resolves #133

### CODE REVIEW

**Comment by GeorgeChatzigiannis** [comment]
Not sure about sod p4 but I gave it a try on era and does throw an error on first load

Interface/AddOns/Talented_SpecTabs/core.lua:36: attempt to compare string with number
[string "@Interface/AddOns/Talented_SpecTabs/core.lua"]:36: in function <Interface/AddOns/Talented_SpecTabs/core.lua:22>
[string "@Interface/AddOns/Talented_SpecTabs/core.lua"]:102: in function `Update'

**Comment by mrchops1024** [comment]
> Not sure about sod p4 but I gave it a try on era and does throw an error on first load
> 
> Interface/AddOns/Talented_SpecTabs/core.lua:36: attempt to compare string with number [string "@Interface/AddOns/Talented_SpecTabs/core.lua"]:36: in function <Interface/AddOns/Talented_SpecTabs/core.lua:22> [string "@Interface/AddOns/Talented_SpecTabs/core.lua"]:102: in function `Update'

Unfortunately I only play SOD right now, so that's all I am able to work on. The Era version was left untouched. It looks like the same error/issue as SOD, so one could theoretically try making the same changes and see if it works.

**Comment by Futzer** [comment]
@mrchops1024 I was getting the same error in Classic Era when attempting to open Talented. When I applied this change locally, it fixed the issue. (I also confirmed that I'm able to view my old talent specs and apply one successfully.) It would be great to get this fix in Era.

By the way, whenever SOD updates, everyone's addons break in Era. Seems like Blizzard always pushes the same scripting API changes to both clients.

Thanks for the awesome addon by the way!

**Comment by GeorgeChatzigiannis** [comment]
Does editing talents work on sod with these changes?

**Comment by mrchops1024** [comment]
> Does editing talents work on sod with these changes?

Yes, I just leveled to 51 and added a talent point.

> @mrchops1024 I was getting the same error in Classic Era when attempting to open Talented. When I applied this change locally, it fixed the issue. (I also confirmed that I'm able to view my old talent specs and apply one successfully.) It would be great to get this fix in Era.

I can add the same fixes if everyone thinks it works.

> Thanks for the awesome addon by the way!

I'm not the addon author, just an avid user who wanted to fix it.

**Comment by Lethay** [comment]
Thanks so much for this. I haven't been able to play in months, so having dedicated people here who can fix things is a lifesaver. I appreciate you.

**Pull request merged**
