### PR TITLE
Rewrite Talented_Data

### PR DESCRIPTION
**Pull request by deathcore01**
Rewrite to Ace3, remove unneeded libs, change file structure for better read and support, added deDE to data, activate dissabled events without Gratuity-2.0, this was rewrite to LibGratuity-3.0 now

### CODE REVIEW

**Comment by Lethay** [comment]
Cool, thank you. But why is this necessary?
Also, you said file structure is rewritten but I don't see any changes.

**Comment by Lethay** [comment]
In answer to myself, though it works perfectly for now, old libraries might conflict with other addons later, as we've been finding with LibGratuity-3.0. If it works perfectly with this version, too, I suppose "why not" is the answer, but I do worry that you've wasted your time fixing something not broken!

I'm still at a loss for where/what you've improved file structure - the diffs of most files seem to just be:

```
- remove all lines
+ add all lines again, unchanged
```

**Comment by deathcore01** [comment]
sorry, my english is not the best, i will say the follow: i have changed the file structure, i have added 3 folders, struct: 
Data\
Data\Class
Data\locale

here are the files for classes and the localized data, before it was into the main folder, this was confusing...

now - i think - it can be better handle... 

in terms of LibGratuity-3.0, i have no problems and i use many many addons, if here is a problem - i will find a solution (i hope...)

problem is the language, i'm speak german and it is very complicated for me, to anderstand another language, please report to me in a light way with a example, if this is possible...

**Comment by Lethay** [comment]
Yes. I didn't see that there were new folders, so I was looking for new "structure" in the files. I'll test and accept the request when I can. Thank you for your hard work.

**Comment by deathcore01** [comment]
ok, please show of the another changes, file structure is not the only - and i will say, not file structure, better is folder structure? a this is the little of changes, the other is the important...

**Pull request merged**
